name: Preview PR

on:
  issue_comment:
    types: [created]

jobs:
  preview:
    if: |
      github.event.issue.pull_request &&
      github.event.comment.body == '/preview' &&
      (
        github.event.comment.author_association == 'OWNER' ||
        github.event.comment.author_association == 'MEMBER' ||
        github.event.comment.author_association == 'COLLABORATOR'
      )
    runs-on: ubuntu-latest
    steps:
      - name: Acknowledge the command
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              content: 'rocket'
            });

      - name: Get PR SHA
        id: pr_sha
        uses: actions/github-script@v7
        with:
          script: |
            const response = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            return response.data.head.sha;
          result-encoding: string

      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.pr_sha.outputs.result }}

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy with Wrangler
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          command: versions upload --env preview --preview-alias 'pr-${{ github.event.issue.number }}'
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Post preview link as a comment
        uses: actions/github-script@v7
        env:
          DEPLOYMENT_URL: ${{ steps.deploy.outputs.deployment-url }}
        with:
          script: |
            const body = `✅ Preview deployed: $DEPLOYMENT_URL`;

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: body
            });
